<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="Graph" timestamp="2016-01-30T16:51:03" hostname="localhost" time="5.006" errors="0" tests="2" skipped="0" disabled="0" failures="1">
  <testcase classname="Graph" name="Direction" time="0.002" />
  <testcase classname="Graph" name="Consistency" time="5.004">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at null._onTimeout (/home/codio/workspace/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="AcyclicGraph" timestamp="2016-01-30T16:51:08" hostname="localhost" time="10.002" errors="0" tests="2" skipped="0" disabled="0" failures="2">
  <testcase classname="AcyclicGraph" name="Direction" time="5.002">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at null._onTimeout (/home/codio/workspace/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)]]>
   </failure>
  </testcase>
  <testcase classname="AcyclicGraph" name="Consistency" time="5">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at null._onTimeout (/home/codio/workspace/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Tree" timestamp="2016-01-30T16:51:18" hostname="localhost" time="10.007" errors="0" tests="2" skipped="0" disabled="0" failures="2">
  <testcase classname="Tree" name="Direction" time="5.005">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at null._onTimeout (/home/codio/workspace/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)]]>
   </failure>
  </testcase>
  <testcase classname="Tree" name="Consistency" time="5.002">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at null._onTimeout (/home/codio/workspace/node_modules/grunt-jasmine-nodejs/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>